apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: fixai
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: fixai
    app.kubernetes.io/component: proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
