apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: fixai
  labels:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/part-of: fixai
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
