apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fixai
  labels:
    app.kubernetes.io/part-of: fixai
    app.kubernetes.io/component: proxy
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://flask-app:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
