apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fixai
  labels:
    app.kubernetes.io/part-of: fixai
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask_app'
        static_configs:
          - targets: ['flask-app:5000']
